=== JoergHeseler/sip-example-999999999_111111111111111/999999999_111111111111111/data/color_mixtures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://nfdi4culture.de/decor1"
           xmlns:decor="http://nfdi4culture.de/decor1"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:element name="colorMixtures" type="decor:ColorMixturesType"/>

  <xs:complexType name="ColorMixturesType">
    <xs:sequence>
      <xs:element name="colorMix" type="decor:ColorMixType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ColorMixType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="components" type="decor:ComponentsType"/>
      <xs:element name="technique" type="xs:string"/>
      <xs:element name="applicationAreas" type="decor:ApplicationAreasType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="ComponentsType">
    <xs:sequence>
      <xs:element name="component" type="decor:ComponentType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ComponentType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="ratioFraction" type="xs:decimal" use="required"/>
  </xs:complexType>

  <xs:complexType name="ApplicationAreasType">
    <xs:sequence>
      <xs:element name="area" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== JoergHeseler/sip-example-999999999_111111111111111/999999999_111111111111111_Kakadu/data/color_mixtures.xml
<decor:colorMixtures xmlns:decor="http://nfdi4culture.de/decor1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://nfdi4culture.de/decor1 color_mixtures.xsd">

  <decor:colorMix id="color001">
    <decor:name>Grün 7 (auf Chromoxid-Basis)</decor:name>
    <decor:components>
      <decor:component name="Chromoxid" ratioFraction="0.70" />
      <decor:component name="Eisenoxid" ratioFraction="0.30" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Flügelfedern</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color002">
    <decor:name>Rot 12 (auf Eisenoxid-Basis)</decor:name>
    <decor:components>
      <decor:component name="Eisenoxid" ratioFraction="0.85" />
      <decor:component name="Siliciumdioxid" ratioFraction="0.15" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Kamm</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color003">
    <decor:name>Blau 3 (auf Kobaltbasis)</decor:name>
    <decor:components>
      <decor:component name="Kobaltoxid" ratioFraction="0.80" />
      <decor:component name="Zinnoxid" ratioFraction="0.20" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Augenring</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color004">
    <decor:name>Grün 9 (auf Chrom-Zink-Basis)</decor:name>
    <decor:components>
      <decor:component name="Chromoxid" ratioFraction="0.90" />
      <decor:component name="Zinkoxid" ratioFraction="0.10" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Blätter</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color005">
    <decor:name>Braun 15 (auf Mangan-Eisen-Basis)</decor:name>
    <decor:components>
      <decor:component name="Manganoxid" ratioFraction="0.60" />
      <decor:component name="Eisenoxid" ratioFraction="0.40" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Ast</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color006">
    <decor:name>Blaugrau 6 (auf Kobalt-Nickel-Basis)</decor:name>
    <decor:components>
      <decor:component name="Kobaltoxid" ratioFraction="0.50" />
      <decor:component name="Nickeloxid" ratioFraction="0.50" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Flügelkanten</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color007">
    <decor:name>Violett 4 (auf Mangan-Kobalt-Basis)</decor:name>
    <decor:components>
      <decor:component name="Manganoxid" ratioFraction="0.70" />
      <decor:component name="Kobaltoxid" ratioFraction="0.30" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Schnabelbasis</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

  <decor:colorMix id="color008">
    <decor:name>Gelb 11 (auf Eisen-Antimon-Basis)</decor:name>
    <decor:components>
      <decor:component name="Eisenoxid" ratioFraction="0.60" />
      <decor:component name="Antimonoxid" ratioFraction="0.40" />
    </decor:components>
    <decor:technique>Aufglasurmalerei</decor:technique>
    <decor:applicationAreas>
      <decor:area>Beine</decor:area>
    </decor:applicationAreas>
  </decor:colorMix>

</decor:colorMixtures>
